CREATE TABLE IF NOT EXISTS standardized.development_permit (
  permit_record_id VARCHAR PRIMARY KEY,
  source_id VARCHAR NOT NULL,
  source_object_id VARCHAR NOT NULL,
  permit_id VARCHAR,
  jurisdiction_geoid VARCHAR NOT NULL,
  issue_date DATE,
  permit_type VARCHAR,
  permit_subtype VARCHAR,
  permit_category VARCHAR,
  permit_status VARCHAR,
  full_address VARCHAR,
  work_description VARCHAR,
  parcel_id VARCHAR,
  zoning VARCHAR,
  applicant_name VARCHAR,
  owner_name VARCHAR,
  fees_paid_usd DOUBLE,
  ward VARCHAR,
  neighborhood_cluster VARCHAR,
  latitude DOUBLE,
  longitude DOUBLE,
  source_url VARCHAR NOT NULL,
  source_vintage VARCHAR NOT NULL,
  last_modified_at TIMESTAMP,
  ingestion_run_id VARCHAR NOT NULL,
  UNIQUE(source_id, source_object_id)
);

CREATE TABLE IF NOT EXISTS standardized.environmental_risk_site (
  site_id VARCHAR PRIMARY KEY,
  source_record_id VARCHAR NOT NULL,
  site_name VARCHAR NOT NULL,
  risk_category VARCHAR NOT NULL,
  program_codes VARCHAR,
  interest_types VARCHAR,
  location_address VARCHAR,
  city_name VARCHAR,
  state_code VARCHAR,
  postal_code VARCHAR,
  county_fips VARCHAR,
  latitude DOUBLE NOT NULL,
  longitude DOUBLE NOT NULL,
  active_status VARCHAR,
  source_url VARCHAR NOT NULL,
  source_vintage VARCHAR NOT NULL,
  last_verified_date DATE NOT NULL,
  confidence_level VARCHAR NOT NULL,
  interpretation_note VARCHAR NOT NULL,
  ingestion_run_id VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS standardized.private_investment_discovery (
  candidate_id VARCHAR PRIMARY KEY,
  discovery_source VARCHAR NOT NULL,
  evidence_type VARCHAR NOT NULL,
  company_name VARCHAR,
  candidate_title VARCHAR NOT NULL,
  filing_or_record_type VARCHAR,
  filing_or_record_date DATE,
  project_location_text VARCHAR,
  latitude DOUBLE,
  longitude DOUBLE,
  source_url VARCHAR NOT NULL,
  evidence_excerpt VARCHAR,
  review_status VARCHAR NOT NULL,
  discovered_at TIMESTAMP NOT NULL,
  ingestion_run_id VARCHAR NOT NULL
);
