CREATE TABLE IF NOT EXISTS standardized.public_investment_discovery (
  candidate_id VARCHAR PRIMARY KEY,
  source_award_id VARCHAR NOT NULL,
  award_generated_id VARCHAR,
  recipient_name VARCHAR,
  description VARCHAR,
  award_type VARCHAR,
  award_amount_usd DOUBLE,
  total_outlays_usd DOUBLE,
  infrastructure_obligations_usd DOUBLE,
  infrastructure_outlays_usd DOUBLE,
  start_date DATE,
  end_date DATE,
  base_obligation_date DATE,
  last_modified_date DATE,
  awarding_agency VARCHAR,
  funding_agency VARCHAR,
  place_of_performance VARCHAR,
  place_state_code VARCHAR,
  place_city_code VARCHAR,
  place_zip5 VARCHAR,
  project_type VARCHAR NOT NULL,
  review_status VARCHAR NOT NULL,
  source_url VARCHAR NOT NULL,
  source_vintage VARCHAR NOT NULL,
  ingestion_run_id VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS standardized.property_assessment_record (
  parcel_id VARCHAR PRIMARY KEY,
  internal_id VARCHAR,
  premise_address VARCHAR,
  unit_number VARCHAR,
  record_status VARCHAR,
  property_type VARCHAR,
  use_code VARCHAR,
  land_area_sqft DOUBLE,
  assessment_neighborhood_code VARCHAR,
  assessment_neighborhood_name VARCHAR,
  assessment_subneighborhood VARCHAR,
  ward VARCHAR,
  owner_name VARCHAR,
  tax_class VARCHAR,
  tax_rate DOUBLE,
  prior_assessed_value_usd DOUBLE,
  current_assessed_value_usd DOUBLE,
  proposed_assessed_value_usd DOUBLE,
  annual_tax_usd DOUBLE,
  latest_sale_price_usd DOUBLE,
  latest_sale_date DATE,
  sale_acceptance_code VARCHAR,
  sale_type VARCHAR,
  total_balance_due_usd DOUBLE,
  extract_date DATE,
  source_url VARCHAR NOT NULL,
  source_vintage VARCHAR NOT NULL,
  ingestion_run_id VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS standardized.property_characteristic_residential (
  parcel_id VARCHAR PRIMARY KEY,
  bathrooms DOUBLE,
  half_bathrooms DOUBLE,
  unit_count INTEGER,
  room_count INTEGER,
  bedroom_count INTEGER,
  average_year_built INTEGER,
  year_remodeled INTEGER,
  effective_year_built INTEGER,
  stories DOUBLE,
  latest_sale_date DATE,
  latest_sale_price_usd DOUBLE,
  qualified_sale_flag VARCHAR,
  gross_building_area_sqft DOUBLE,
  style_description VARCHAR,
  structure_description VARCHAR,
  grade_description VARCHAR,
  condition_description VARCHAR,
  land_area_sqft DOUBLE,
  last_modified_at TIMESTAMP,
  source_url VARCHAR NOT NULL,
  source_vintage VARCHAR NOT NULL,
  ingestion_run_id VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS meta.market_rollout (
  market_id VARCHAR PRIMARY KEY,
  market_name VARCHAR NOT NULL,
  cbsa_code VARCHAR NOT NULL,
  priority_tier INTEGER NOT NULL,
  rollout_status VARCHAR NOT NULL,
  public_record_strategy VARCHAR NOT NULL,
  listing_strategy VARCHAR NOT NULL,
  transit_strategy VARCHAR NOT NULL,
  notes VARCHAR
);
