CREATE TABLE IF NOT EXISTS standardized.private_investment_project (
  project_id text PRIMARY KEY,
  company_name text NOT NULL,
  project_name text,
  investment_type text NOT NULL,
  project_status text NOT NULL,
  announcement_date date,
  expected_open_date date,
  capex_usd numeric,
  expected_jobs integer,
  county_geoid char(5) NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  coordinate_precision text NOT NULL,
  primary_source_url text NOT NULL,
  verification_status text NOT NULL,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id),
  evidence_type text NOT NULL DEFAULT 'OTHER',
  funding_status text NOT NULL DEFAULT 'UNKNOWN',
  committed_capex_usd numeric,
  financing_status text,
  actual_open_date date,
  secondary_source_url text,
  source_document_date date,
  last_verified_date date,
  confidence_level text NOT NULL DEFAULT 'LOW'
);
CREATE TABLE IF NOT EXISTS standardized.public_investment_project (
  project_id text PRIMARY KEY,
  project_name text NOT NULL,
  sponsor_name text NOT NULL,
  project_type text NOT NULL,
  project_status text NOT NULL,
  funding_status text NOT NULL,
  announcement_date date,
  approval_date date,
  construction_start_date date,
  expected_completion_date date,
  actual_completion_date date,
  total_project_cost_usd numeric,
  proposed_funding_usd numeric,
  budgeted_funding_usd numeric,
  appropriated_funding_usd numeric,
  awarded_funding_usd numeric,
  spent_funding_usd numeric,
  geography_type text NOT NULL,
  geography_id text NOT NULL,
  county_geoid char(5),
  tract_geoid char(11),
  latitude numeric,
  longitude numeric,
  coordinate_precision text,
  primary_source_url text NOT NULL,
  secondary_source_url text,
  source_document_date date,
  last_verified_date date NOT NULL,
  verification_status text NOT NULL,
  confidence_level text NOT NULL,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id)
);

CREATE TABLE IF NOT EXISTS standardized.regulatory_policy (
  policy_id text PRIMARY KEY,
  jurisdiction_type text NOT NULL,
  state_fips char(2) NOT NULL,
  county_geoid char(5),
  place_geoid char(7),
  jurisdiction_name text NOT NULL,
  policy_category text NOT NULL,
  policy_dimension text NOT NULL,
  policy_summary text NOT NULL,
  effective_date date,
  expiration_date date,
  official_citation text,
  official_source_url text NOT NULL,
  last_verified_date date NOT NULL,
  review_status text NOT NULL,
  confidence_level text NOT NULL,
  applicability_note text,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id)
);

CREATE TABLE IF NOT EXISTS standardized.environmental_risk_observation (
  observation_id text PRIMARY KEY,
  source_record_id text,
  geography_type text NOT NULL,
  geography_id text NOT NULL,
  geography_vintage text,
  risk_category text NOT NULL,
  metric_id text NOT NULL,
  value_numeric numeric,
  value_text text,
  unit text,
  observation_date date,
  reference_period_start date,
  reference_period_end date,
  source_vintage text NOT NULL,
  publication_date date,
  source_url text NOT NULL,
  assignment_method text NOT NULL,
  review_status text NOT NULL,
  confidence_level text NOT NULL,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id),
  CHECK (value_numeric IS NOT NULL OR value_text IS NOT NULL)
);
