CREATE TABLE IF NOT EXISTS standardized.development_permit (
  permit_record_id text PRIMARY KEY,
  source_id text NOT NULL,
  source_object_id text NOT NULL,
  permit_id text,
  jurisdiction_geoid text NOT NULL,
  issue_date date,
  permit_type text,
  permit_subtype text,
  permit_category text,
  permit_status text,
  full_address text,
  work_description text,
  parcel_id text,
  zoning text,
  applicant_name text,
  owner_name text,
  fees_paid_usd numeric,
  ward text,
  neighborhood_cluster text,
  latitude numeric,
  longitude numeric,
  source_url text NOT NULL,
  source_vintage text NOT NULL,
  last_modified_at timestamp,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id),
  UNIQUE(source_id, source_object_id)
);

CREATE TABLE IF NOT EXISTS standardized.environmental_risk_site (
  site_id text PRIMARY KEY,
  source_record_id text NOT NULL,
  site_name text NOT NULL,
  risk_category text NOT NULL,
  program_codes text,
  interest_types text,
  location_address text,
  city_name text,
  state_code text,
  postal_code text,
  county_fips char(5),
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  active_status text,
  source_url text NOT NULL,
  source_vintage text NOT NULL,
  last_verified_date date NOT NULL,
  confidence_level text NOT NULL,
  interpretation_note text NOT NULL,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id)
);

CREATE TABLE IF NOT EXISTS standardized.private_investment_discovery (
  candidate_id text PRIMARY KEY,
  discovery_source text NOT NULL,
  evidence_type text NOT NULL,
  company_name text,
  candidate_title text NOT NULL,
  filing_or_record_type text,
  filing_or_record_date date,
  project_location_text text,
  latitude numeric,
  longitude numeric,
  source_url text NOT NULL,
  evidence_excerpt text,
  review_status text NOT NULL,
  discovered_at timestamp NOT NULL,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id)
);
