CREATE TABLE IF NOT EXISTS standardized.public_investment_discovery (
  candidate_id text PRIMARY KEY,
  source_award_id text NOT NULL,
  award_generated_id text,
  recipient_name text,
  description text,
  award_type text,
  award_amount_usd numeric,
  total_outlays_usd numeric,
  infrastructure_obligations_usd numeric,
  infrastructure_outlays_usd numeric,
  start_date date,
  end_date date,
  base_obligation_date date,
  last_modified_date date,
  awarding_agency text,
  funding_agency text,
  place_of_performance text,
  place_state_code text,
  place_city_code text,
  place_zip5 text,
  project_type text NOT NULL,
  review_status text NOT NULL,
  source_url text NOT NULL,
  source_vintage text NOT NULL,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id)
);

CREATE TABLE IF NOT EXISTS standardized.property_assessment_record (
  parcel_id text PRIMARY KEY,
  internal_id text,
  premise_address text,
  unit_number text,
  record_status text,
  property_type text,
  use_code text,
  land_area_sqft numeric,
  assessment_neighborhood_code text,
  assessment_neighborhood_name text,
  assessment_subneighborhood text,
  ward text,
  owner_name text,
  tax_class text,
  tax_rate numeric,
  prior_assessed_value_usd numeric,
  current_assessed_value_usd numeric,
  proposed_assessed_value_usd numeric,
  annual_tax_usd numeric,
  latest_sale_price_usd numeric,
  latest_sale_date date,
  sale_acceptance_code text,
  sale_type text,
  total_balance_due_usd numeric,
  extract_date date,
  source_url text NOT NULL,
  source_vintage text NOT NULL,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id)
);

CREATE TABLE IF NOT EXISTS standardized.property_characteristic_residential (
  parcel_id text PRIMARY KEY,
  bathrooms numeric,
  half_bathrooms numeric,
  unit_count integer,
  room_count integer,
  bedroom_count integer,
  average_year_built integer,
  year_remodeled integer,
  effective_year_built integer,
  stories numeric,
  latest_sale_date date,
  latest_sale_price_usd numeric,
  qualified_sale_flag text,
  gross_building_area_sqft numeric,
  style_description text,
  structure_description text,
  grade_description text,
  condition_description text,
  land_area_sqft numeric,
  last_modified_at timestamp,
  source_url text NOT NULL,
  source_vintage text NOT NULL,
  ingestion_run_id uuid NOT NULL REFERENCES meta.ingestion_run(run_id)
);

CREATE TABLE IF NOT EXISTS meta.market_rollout (
  market_id text PRIMARY KEY,
  market_name text NOT NULL,
  cbsa_code char(5) NOT NULL,
  priority_tier integer NOT NULL,
  rollout_status text NOT NULL,
  public_record_strategy text NOT NULL,
  listing_strategy text NOT NULL,
  transit_strategy text NOT NULL,
  notes text
);
